<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = new User();
        $user->name = 'User';
        $user->email = 'user@eternity.com';
        $user->eternite1 = 20000;
        $user->password = Hash::make('wars1234');
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->escape = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'asd';
        $user->referral_answer = 'basd';
        $user->save();

        $user = new User();
        $user->name = 'Admin';
        $user->email = 'admin@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('wars1234');
        $user->save();

        $user = new User();
        $user->name = '001-cuanciak';
        $user->email = 'Player001@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 1;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '21UGF12FDR';
        $user->referral_answer = '8IANDJDOXA';
        $user->password = Hash::make('esc6017001');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '002-The Boomers';
        $user->email = 'Player002@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 2;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'QEVP1MMCER';
        $user->referral_answer = '8MDLS9UPCK';
        $user->password = Hash::make('6017002esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '003-GGANBU';
        $user->email = 'Player003@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 3;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'Z8UK3BCOUS';
        $user->referral_answer = 'D5X7GDA27Y';
        $user->password = Hash::make('esc0617003');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '004-Pengwins';
        $user->email = 'Player004@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 4;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'JWQFIS72X9';
        $user->referral_answer = 'KXTWQFSK91';
        $user->password = Hash::make('0617004esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '005-Gyro';
        $user->email = 'Player005@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 5;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'CS40MAGLYH';
        $user->referral_answer = 'VFQXBES5PB';
        $user->password = Hash::make('esc6071005');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '006-JIKJIN';
        $user->email = 'Player006@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 6;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8IANDJDOXA';
        $user->referral_answer = '21UGF12FDR';
        $user->password = Hash::make('6071006esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '007-SMA DHARMA LOKA';
        $user->email = 'Player007@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 7;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8MDLS9UPCK';
        $user->referral_answer = 'QEVP1MMCER';
        $user->password = Hash::make('esc0671007');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '008-Daisy';
        $user->email = 'Player008@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 8;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'D5X7GDA27Y';
        $user->referral_answer = 'Z8UK3BCOUS';
        $user->password = Hash::make('0671008esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '009-Pepega';
        $user->email = 'Player009@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 9;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'KXTWQFSK91';
        $user->referral_answer = 'JWQFIS72X9';
        $user->password = Hash::make('esc6017009');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '010-CAT';
        $user->email = 'Player010@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 10;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'VFQXBES5PB';
        $user->referral_answer = 'CS40MAGLYH';
        $user->password = Hash::make('6017010esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '011-Sumber Makmur';
        $user->email = 'Player011@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 1;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '21UGF12FDR';
        $user->referral_answer = '8IANDJDOXA';
        $user->password = Hash::make('esc0617011');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '012-JPC';
        $user->email = 'Player012@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 2;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'QEVP1MMCER';
        $user->referral_answer = '8MDLS9UPCK';
        $user->password = Hash::make('0617012esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '013-Chandelle';
        $user->email = 'Player013@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 3;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'Z8UK3BCOUS';
        $user->referral_answer = 'D5X7GDA27Y';
        $user->password = Hash::make('esc6071013');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '014-Gaje';
        $user->email = 'Player014@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 4;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'JWQFIS72X9';
        $user->referral_answer = 'KXTWQFSK91';
        $user->password = Hash::make('6071014esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '015-Trio kwek kwek';
        $user->email = 'Player015@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 5;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'CS40MAGLYH';
        $user->referral_answer = 'VFQXBES5PB';
        $user->password = Hash::make('esc0671015');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '016-TheMerge';
        $user->email = 'Player016@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 6;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8IANDJDOXA';
        $user->referral_answer = '21UGF12FDR';
        $user->password = Hash::make('0671016esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '017-Arcane';
        $user->email = 'Player017@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 7;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8MDLS9UPCK';
        $user->referral_answer = 'QEVP1MMCER';
        $user->password = Hash::make('esc6017017');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '018-MasakoMantoel';
        $user->email = 'Player018@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 8;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'D5X7GDA27Y';
        $user->referral_answer = 'Z8UK3BCOUS';
        $user->password = Hash::make('6017018esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '019-Cuan';
        $user->email = 'Player019@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 9;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'KXTWQFSK91';
        $user->referral_answer = 'JWQFIS72X9';
        $user->password = Hash::make('esc0617019');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '020-Stonks';
        $user->email = 'Player020@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 10;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'VFQXBES5PB';
        $user->referral_answer = 'CS40MAGLYH';
        $user->password = Hash::make('0617020esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '021-Nekatin Aja';
        $user->email = 'Player021@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 1;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '21UGF12FDR';
        $user->referral_answer = '8IANDJDOXA';
        $user->password = Hash::make('esc6071021');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '022-Tut';
        $user->email = 'Player022@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 2;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'QEVP1MMCER';
        $user->referral_answer = '8MDLS9UPCK';
        $user->auction_q = 2;
        $user->password = Hash::make('6071022esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '023-Daddy Roy';
        $user->email = 'Player023@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 3;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'Z8UK3BCOUS';
        $user->referral_answer = 'D5X7GDA27Y';
        $user->password = Hash::make('esc0671023');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '024-CAKAR SERIGALA';
        $user->email = 'Player024@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 4;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'JWQFIS72X9';
        $user->referral_answer = 'KXTWQFSK91';
        $user->password = Hash::make('0671024esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '025-LOMONEY';
        $user->email = 'Player025@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 5;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'CS40MAGLYH';
        $user->referral_answer = 'VFQXBES5PB';
        $user->password = Hash::make('esc6017025');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '026-Eternite';
        $user->email = 'Player026@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 6;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8IANDJDOXA';
        $user->referral_answer = '21UGF12FDR';
        $user->password = Hash::make('6017026esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '027-Bebas';
        $user->email = 'Player027@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 7;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8MDLS9UPCK';
        $user->referral_answer = 'QEVP1MMCER';
        $user->password = Hash::make('esc0617027');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '028-Uptrend';
        $user->email = 'Player028@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 8;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'D5X7GDA27Y';
        $user->referral_answer = 'Z8UK3BCOUS';
        $user->password = Hash::make('0617028esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '029-High SEDES';
        $user->email = 'Player029@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 9;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'KXTWQFSK91';
        $user->referral_answer = 'JWQFIS72X9';
        $user->password = Hash::make('esc6071029');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '030-FTW';
        $user->email = 'Player030@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 10;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'VFQXBES5PB';
        $user->referral_answer = 'CS40MAGLYH';
        $user->password = Hash::make('6071030esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '031-SMANSA DC';
        $user->email = 'Player031@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 1;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '21UGF12FDR';
        $user->referral_answer = '8IANDJDOXA';
        $user->password = Hash::make('esc0671031');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '032-H2SO4';
        $user->email = 'Player032@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 2;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'QEVP1MMCER';
        $user->referral_answer = '8MDLS9UPCK';
        $user->password = Hash::make('0671032esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '033-WFH';
        $user->email = 'Player033@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 3;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'Z8UK3BCOUS';
        $user->referral_answer = 'D5X7GDA27Y';
        $user->password = Hash::make('esc6017034');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '034-bolte';
        $user->email = 'Player034@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 4;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'JWQFIS72X9';
        $user->referral_answer = 'KXTWQFSK91';
        $user->password = Hash::make('6017035esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '035-THREE MUSKETEERS';
        $user->email = 'Player035@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 5;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'CS40MAGLYH';
        $user->referral_answer = 'VFQXBES5PB';
        $user->password = Hash::make('esc0617035');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '036-ASN';
        $user->email = 'Player036@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 6;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8IANDJDOXA';
        $user->referral_answer = '21UGF12FDR';
        $user->password = Hash::make('0617036esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '037-Katoda';
        $user->email = 'Player037@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 7;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8MDLS9UPCK';
        $user->referral_answer = 'QEVP1MMCER';
        $user->password = Hash::make('esc6071037');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '038-Endeavour';
        $user->email = 'Player038@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 8;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'D5X7GDA27Y';
        $user->referral_answer = 'Z8UK3BCOUS';
        $user->password = Hash::make('e6071038esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '039-IMMORTAL';
        $user->email = 'Player039@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 9;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'KXTWQFSK91';
        $user->referral_answer = 'JWQFIS72X9';
        $user->password = Hash::make('esc0671039');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '040-DREAM CATCHER';
        $user->email = 'Player040@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 10;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'VFQXBES5PB';
        $user->referral_answer = 'CS40MAGLYH';
        $user->password = Hash::make('0671040esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '041-Nyasar';
        $user->email = 'Player041@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 1;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '21UGF12FDR';
        $user->referral_answer = '8IANDJDOXA';
        $user->password = Hash::make('esc6017041');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '042-Bisniche';
        $user->email = 'Player042@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 2;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'QEVP1MMCER';
        $user->referral_answer = '8MDLS9UPCK';
        $user->password = Hash::make('6017042esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '043-MVP';
        $user->email = 'Player043@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 3;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'Z8UK3BCOUS';
        $user->referral_answer = 'D5X7GDA27Y';
        $user->password = Hash::make('esc0617043');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '044-Emotional Demeg';
        $user->email = 'Player044@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 4;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'JWQFIS72X9';
        $user->referral_answer = 'KXTWQFSK91';
        $user->password = Hash::make('0617044esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '045-Pasti Menang';
        $user->email = 'Player045@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 5;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'CS40MAGLYH';
        $user->referral_answer = 'VFQXBES5PB';
        $user->password = Hash::make('esc6071045');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '046-Beyonders';
        $user->email = 'Player046@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 6;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8IANDJDOXA';
        $user->referral_answer = '21UGF12FDR';
        $user->password = Hash::make('6071046esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '047-Deradadum';
        $user->email = 'Player047@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 7;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8MDLS9UPCK';
        $user->referral_answer = 'QEVP1MMCER';
        $user->password = Hash::make('esc0671047');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '048-UNCLASSIFIED';
        $user->email = 'Player048@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 8;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'D5X7GDA27Y';
        $user->referral_answer = 'Z8UK3BCOUS';
        $user->password = Hash::make('0671048esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '049-ayang bisnis';
        $user->email = 'Player049@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 9;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'KXTWQFSK91';
        $user->referral_answer = 'JWQFIS72X9';
        $user->password = Hash::make('esc6017049');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '050-Aladdin';
        $user->email = 'Player050@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 10;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'VFQXBES5PB';
        $user->referral_answer = 'CS40MAGLYH';
        $user->password = Hash::make('6017050esc');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '051-PLAYER';
        $user->email = 'Player051@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 1;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '21UGF12FDR';
        $user->referral_answer = '8IANDJDOXA';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '052-PLAYER';
        $user->email = 'Player052@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 2;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'QEVP1MMCER';
        $user->referral_answer = '8MDLS9UPCK';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '053-PLAYER';
        $user->email = 'Player053@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 3;
        $user->question_pack = 3;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'Z8UK3BCOUS';
        $user->referral_answer = 'D5X7GDA27Y';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '054-PLAYER';
        $user->email = 'Player054@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 4;
        $user->question_pack = 1;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'JWQFIS72X9';
        $user->referral_answer = 'KXTWQFSK91';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '055-PLAYER';
        $user->email = 'Player055@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 5;
        $user->question_pack = 2;
        $user->map_type = 1;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'CS40MAGLYH';
        $user->referral_answer = 'VFQXBES5PB';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '056-PLAYER';
        $user->email = 'Player056@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 6;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8IANDJDOXA';
        $user->referral_answer = '21UGF12FDR';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '057-PLAYER';
        $user->email = 'Player057@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 7;
        $user->question_pack = 1;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = '8MDLS9UPCK';
        $user->referral_answer = 'QEVP1MMCER';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '058-PLAYER';
        $user->email = 'Player058@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 8;
        $user->question_pack = 2;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'D5X7GDA27Y';
        $user->referral_answer = 'Z8UK3BCOUS';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '059-PLAYERr';
        $user->email = 'Player059@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 9;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'KXTWQFSK91';
        $user->referral_answer = 'JWQFIS72X9';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();

        $user = new User();
        $user->name = '060-PLAYER';
        $user->email = 'Player060@eternity.com';
        $user->eternite1 = 20000;
        $user->flour = 100;
        $user->egg = 100;
        $user->meat = 100;
        $user->oil = 100;
        $user->iron = 100;
        $user->wood = 100;
        $user->cloth = 100;
        $user->auction_q = 10;
        $user->question_pack = 3;
        $user->map_type = 2;
        $user->easy = 1;
        $user->medium = 1;
        $user->hard = 1;
        $user->referral_code = 'VFQXBES5PB';
        $user->referral_answer = 'CS40MAGLYH';
        $user->password = Hash::make('PANITIAAA');
        $user->escape = 1;
        $user->save();






        $user = new User();
        $user->name = 'Admin01';
        $user->email = 'admin01@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin02';
        $user->email = 'admin02@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin03';
        $user->email = 'admin03@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin04';
        $user->email = 'admin04@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin05';
        $user->email = 'admin05@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin06';
        $user->email = 'admin06@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin07';
        $user->email = 'admin07@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin08';
        $user->email = 'admin08@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin09';
        $user->email = 'admin09@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin10';
        $user->email = 'admin10@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin11';
        $user->email = 'admin11@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin12';
        $user->email = 'admin12@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin13';
        $user->email = 'admin13@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin14';
        $user->email = 'admin14@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin15';
        $user->email = 'admin15@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin16';
        $user->email = 'admin16@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin17';
        $user->email = 'admin17@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin18';
        $user->email = 'admin18@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin19';
        $user->email = 'admin19@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin20';
        $user->email = 'admin20@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin21';
        $user->email = 'admin21@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin22';
        $user->email = 'admin22@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin23';
        $user->email = 'admin23@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin24';
        $user->email = 'admin24@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin25';
        $user->email = 'admin25@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin26';
        $user->email = 'admin26@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin27';
        $user->email = 'admin27@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin28';
        $user->email = 'admin28@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin29';
        $user->email = 'admin29@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin30';
        $user->email = 'admin30@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin31';
        $user->email = 'admin31@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin32';
        $user->email = 'admin32@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin33';
        $user->email = 'admin33@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin34';
        $user->email = 'admin34@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin35';
        $user->email = 'admin35@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin36';
        $user->email = 'admin36@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin37';
        $user->email = 'admin37@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin38';
        $user->email = 'admin38@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin39';
        $user->email = 'admin39@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();

        $user = new User();
        $user->name = 'Admin40';
        $user->email = 'admin40@eternity.com';
        $user->eternite1 = 0;
        $user->role = 1;
        $user->password = Hash::make('admin');
        $user->save();
    }
}
