module.exports = {
    purge: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            backgroundImage: {
                "e-flower": "url('/svg/e-flower.svg')",
                "e-grid-black": "url('/svg/background.svg')",
                "lb-rt-frame": "url('/svg/lb-rt-frame.svg')",
                "lb-rt-dashboard-frame": "url('/svg/lb-rt-frame.svg')",
                "lt-rb-frame": "url('/svg/lt-rb-frame.svg')",
                "lt-frame": "url('/svg/lt-frame.svg')",
                "lt-rb-long-frame": "url('/svg/lt-rb-long-frame.svg')",
                "lt-rt-frame": "url('/svg/lt-rt-frame.svg')",
                "lt-small-frame": "url('/svg/lt-small-frame.svg')",
                "rt-frame": "url('/svg/rt-frame.svg')",
                "box-frame": "url('/svg/box-frame.svg')",
                "rally-zoom": "url('/svg/rally-zoom.svg')",
                "market-left": "url('/svg/market-left.svg')",
                "market-middle": "url('/svg/market-middle.svg')",
                "market-right": "url('/svg/market-right.svg')",
                "lucky-draw-box": "url('/svg/lucky-draw-box.svg')",
                "ship-1": "url('/svg/ship-1.svg')",
                "ship-2": "url('/svg/ship-2.svg')",
                "ship-3": "url('/svg/ship-3.svg')",
                "ship-4": "url('/svg/ship-4.svg')",
                "ship-5": "url('/svg/ship-5.svg')",
                "ship-6": "url('/svg/ship-6.svg')",
                //background
                "starting-point": "url('/svg/starting-point.svg')",
                "easy-room": "url('/svg/easy-room.svg')",
                "medium-room": "url('/svg/medium-room.svg')",
                "hard-room": "url('/svg/hard-room.svg')",
                //item
                "easy-red": "url('/svg/easy-red.svg')",
                "easy-red-hover": "url('/svg/easy-red-hover.svg')",
                "easy-green": "url('/svg/easy-green.svg')",
                "easy-green-hover": "url('/svg/easy-green-hover.svg')",
                "medium-red": "url('/svg/medium-red.svg')",
                "medium-red-hover": "url('/svg/medium-red-hover.svg')",
                "medium-green": "url('/svg/medium-green.svg')",
                "medium-green-hover": "url('/svg/medium-green-hover.svg')",
                "hard-red": "url('/svg/hard-red.svg')",
                "hard-red-hover": "url('/svg/hard-red-hover.svg')",
                "hard-green": "url('/svg/hard-green.svg')",
                "hard-green-hover": "url('/svg/hard-green-hover.svg')",
                paper: "url('/svg/paper.svg')",
                "paper-hover": "url('/svg/paper-hover.svg')",
                //map
                "map-1a": "url('/svg/1a.svg')",
                "map-1a-hover": "url('/svg/1a-hover.svg')",
                "map-1b": "url('/svg/1b.svg')",
                "map-1b-hover": "url('/svg/1b-hover.svg')",
                "map-2a": "url('/svg/2a.svg')",
                "map-2a-hover": "url('/svg/2a-hover.svg')",
                "map-2b": "url('/svg/2b.svg')",
                "map-2b-hover": "url('/svg/2b-hover.svg')",
                "map-3a": "url('/svg/3a.svg')",
                "map-3a-hover": "url('/svg/3a-hover.svg')",
                "map-3b": "url('/svg/3b.svg')",
                "map-3b-hover": "url('/svg/3b-hover.svg')",
                "map-4a": "url('/svg/4a.svg')",
                "map-4a-hover": "url('/svg/4a-hover.svg')",
                "map-4b": "url('/svg/4b.svg')",
                "map-4b-hover": "url('/svg/4b-hover.svg')",
                "map-5a": "url('/svg/5a.svg')",
                "map-5a-hover": "url('/svg/5a-hover.svg')",
                "map-5b": "url('/svg/5b.svg')",
                "map-5b-hover": "url('/svg/5b-hover.svg')",
                "map-6a": "url('/svg/6a.svg')",
                "map-6a-hover": "url('/svg/6a-hover.svg')",
                "map-6b": "url('/svg/6b.svg')",
                "map-6b-hover": "url('/svg/6b-hover.svg')",
                "map-7a": "url('/svg/7a.svg')",
                "map-7a-hover": "url('/svg/7a-hover.svg')",
                "map-7b": "url('/svg/7b.svg')",
                "map-7b-hover": "url('/svg/7b-hover.svg')",
                "map-8a": "url('/svg/8a.svg')",
                "map-8a-hover": "url('/svg/8a-hover.svg')",
                "map-8b": "url('/svg/8b.svg')",
                "map-8b-hover": "url('/svg/8b-hover.svg')",
                "map-9a": "url('/svg/9a.svg')",
                "map-9a-hover": "url('/svg/9a-hover.svg')",
                "map-9b": "url('/svg/9b.svg')",
                "map-9b-hover": "url('/svg/9b-hover.svg')",
                "map-10a": "url('/svg/10a.svg')",
                "map-10a-hover": "url('/svg/10a-hover.svg')",
                "map-10b": "url('/svg/10b.svg')",
                "map-10b-hover": "url('/svg/10b-hover.svg')",
                "map-11a": "url('/svg/11a.svg')",
                "map-11a-hover": "url('/svg/11a-hover.svg')",
                "map-11b": "url('/svg/11b.svg')",
                "map-11b-hover": "url('/svg/11b-hover.svg')",
                "map-12a": "url('/svg/12a.svg')",
                "map-12a-hover": "url('/svg/12a-hover.svg')",
                "map-12b": "url('/svg/12b.svg')",
                "map-12b-hover": "url('/svg/12b-hover.svg')",
                "map-13a": "url('/svg/13a.svg')",
                "map-13a-hover": "url('/svg/13a-hover.svg')",
                "map-13b": "url('/svg/13b.svg')",
                "map-13b-hover": "url('/svg/13b-hover.svg')",
                "map-14a": "url('/svg/14a.svg')",
                "map-14a-hover": "url('/svg/14a-hover.svg')",
                "map-14b": "url('/svg/14b.svg')",
                "map-14b-hover": "url('/svg/14b-hover.svg')",
                "map-15a": "url('/svg/15a.svg')",
                "map-15a-hover": "url('/svg/15a-hover.svg')",
                "map-15b": "url('/svg/15b.svg')",
                "map-15b-hover": "url('/svg/15b-hover.svg')",
                "map-16a": "url('/svg/16a.svg')",
                "map-16a-hover": "url('/svg/16a-hover.svg')",
                "map-16b": "url('/svg/16b.svg')",
                "map-16b-hover": "url('/svg/16b-hover.svg')",
                "map-17a": "url('/svg/17a.svg')",
                "map-17a-hover": "url('/svg/17a-hover.svg')",
                "map-17b": "url('/svg/17b.svg')",
                "map-17b-hover": "url('/svg/17b-hover.svg')",
                "map-18a": "url('/svg/18a.svg')",
                "map-18a-hover": "url('/svg/18a-hover.svg')",
                "map-18b": "url('/svg/18b.svg')",
                "map-18b-hover": "url('/svg/18b-hover.svg')",
                "map-19a": "url('/svg/19a.svg')",
                "map-19a-hover": "url('/svg/19a-hover.svg')",
                "map-19b": "url('/svg/19b.svg')",
                "map-19b-hover": "url('/svg/19b-hover.svg')",
                "map-20a": "url('/svg/20a.svg')",
                "map-20a-hover": "url('/svg/20a-hover.svg')",
                "map-20b": "url('/svg/20b.svg')",
                "map-20b-hover": "url('/svg/20b-hover.svg')",

                //easy room
                "easy-book-1": "url('/png/easy-book-1.png')",
                "easy-book-1-hover": "url('/png/easy-book-1-hover.png')",
                "easy-book-2": "url('/png/easy-book-2.png')",
                "easy-book-2-hover": "url('/png/easy-book-2-hover.png')",
                "easy-book-3": "url('/png/easy-book-3.png')",
                "easy-book-3-hover": "url('/png/easy-book-3-hover.png')",
                "easy-book-4": "url('/png/easy-book-4.png')",
                "easy-book-4-hover": "url('/png/easy-book-4-hover.png')",
                "easy-carpet": "url('/png/easy-carpet.png')",
                "easy-carpet-hover": "url('/png/easy-carpet-hover.png')",
                "easy-curtain-left": "url('/png/easy-curtain-1.png')",
                "easy-curtain-left-hover":
                    "url('/png/easy-curtain-1-hover.png')",
                "easy-curtain-right": "url('/png/easy-curtain-2.png')",
                "easy-curtain-right-hover":
                    "url('/png/easy-curtain-2-hover.png')",
                "easy-frame-1": "url('/png/easy-frame-1.png')",
                "easy-frame-1-hover": "url('/png/easy-frame-1-hover.png')",
                "easy-frame-2": "url('/png/easy-frame-2.png')",
                "easy-frame-2-hover": "url('/png/easy-frame-2-hover.png')",
                "easy-frame-3": "url('/png/easy-frame-3.png')",
                "easy-frame-3-hover": "url('/png/easy-frame-3-hover.png')",
                "easy-mirror": "url('/png/easy-mirror.png')",
                "easy-mirror-hover": "url('/png/easy-mirror-hover.png')",
                "easy-lamp": "url('/png/easy-lamp.png')",
                "easy-lamp-hover": "url('/png/easy-lamp-hover.png')",
                "easy-plant": "url('/png/easy-plant.png')",
                "easy-plant-hover": "url('/png/easy-plant-hover.png')",
                "easy-sofa-hover": "url('/png/easy-sofa-hover.png')",
                "easy-sofa": "url('/png/easy-sofa.png')",
                "easy-tv-hover": "url('/png/easy-tv-hover.png')",
                "easy-tv": "url('/png/easy-tv.png')",

                //medium room
                "medium-alarm": "url('/svg/medium-alarm.svg')",
                "medium-alarm-hover": "url('/svg/medium-alarm-hover.svg')",
                "medium-basket": "url('/svg/medium-basket.svg')",
                "medium-basket-hover": "url('/svg/medium-basket-hover.svg')",
                "medium-book": "url('/svg/medium-book.svg')",
                "medium-book-hover": "url('/svg/medium-book-hover.svg')",
                "medium-books": "url('/svg/medium-books.svg')",
                "medium-books-hover": "url('/svg/medium-books-hover.svg')",
                "medium-frame-1": "url('/svg/medium-frame-1.svg')",
                "medium-frame-1-hover": "url('/svg/medium-frame-1-hover.svg')",
                "medium-frame-2": "url('/svg/medium-frame-2.svg')",
                "medium-frame-2-hover": "url('/svg/medium-frame-2-hover.svg')",
                "medium-frame-3": "url('/svg/medium-frame-3.svg')",
                "medium-frame-3-hover": "url('/svg/medium-frame-3-hover.svg')",
                "medium-frame-4": "url('/svg/medium-frame-4.svg')",
                "medium-frame-4-hover": "url('/svg/medium-frame-4-hover.svg')",
                "medium-lamp": "url('/svg/medium-lamp.svg')",
                "medium-lamp-hover": "url('/svg/medium-lamp-hover.svg')",
                "medium-parfume": "url('/svg/medium-parfumee.svg')",
                "medium-parfume-hover": "url('/svg/medium-parfumee-hover.svg')",
                "medium-shelf-closed": "url('/svg/medium-shelf-closed.svg')",
                "medium-shelf-closed-hover": "url('/svg/medium-shelf-closed-hover.svg')",
                "medium-shelf-open-left": "url('/svg/medium-shelf-open-left.svg')",
                "medium-shelf-open-left-hover": "url('/svg/medium-shelf-open-left-hover.svg')",
                "medium-shelf-open-right": "url('/svg/medium-shelf-open-right.svg')",
                "medium-shelf-open-right-hover": "url('/svg/medium-shelf-open-right-hover.svg')",

                "dice-1": "url('/svg/dice-1.svg')",
                "dice-2": "url('/svg/dice-2.svg')",
                "dice-3": "url('/svg/dice-3.svg')",
                "dice-4": "url('/svg/dice-4.svg')",
                "dice-5": "url('/svg/dice-5.svg')",
                "dice-6": "url('/svg/dice-6.svg')",
                "magnet": "url('/svg/magnet.svg')",
                "teleport": "url('/svg/teleport.svg')",
                "freepass": "url('/svg/freepass.svg')",
                "timestwo": "url('/svg/timestwo.svg')",
            },
            colors: {
                "eternity-6-blue": "#2484C6",
                "eternity-6-orange": "#D55023",
                "eternity-6-black": "#231f20",
                "eternity-6-brown": "#2f292b",
                "eternity-6-gray": "#827e7b",
                "eternity-6-red": "#c14d45",
                "eternity-6-green": "#1db954",
            },
            fontFamily: {
                audiowide: ['"audiowide"'],
                montserrat: ['"Montserrat"'],
            },
            spacing: {
                108: "28rem",
                112: "32rem",
                128: "36rem",
                136: "40rem",
                142: "44rem",
                148: "48rem",
            },
            margin: {
                "1/10": "10%",
                "1.5/10": "15%",
                "2/10": "20%",
                "3/10": "30%",
                "3.5/10": "35%",
                "4/10": "40%",
                "5/10": "50%",
                "6/10": "60%",
                "7/10": "70%",
                "8/10": "80%",
                "9/10": "90%",
            },
            width: {
                "vw-30": "30vw",
                "vw-40": "40vw",
                "vw-50": "50vw",
                "vw-55": "55vw",
                "vw-60": "60vw",
                "vw-65": "65vw",
                "vw-70": "70vw",
                "vw-80": "80vw",
                "vw-90": "90vw",
                "1/10": "10%",
                "2/10": "20%",
                "3/10": "30%",
                "3.5/10": "35%",
                "4/10": "40%",
                "5/10": "50%",
                "6/10": "60%",
                "7/10": "70%",
                "8/10": "80%",
                "9/10": "90%",
                "2px": "2px",
            },
            height: {
                "vh-5": "5vh",
                "vh-10": "10vh",
                "vh-20": "20vh",
                "vh-25": "25vh",
                "vh-30": "30vh",
                "vh-40": "40vh",
                "vh-50": "50vh",
                "vh-55": "55vh",
                "vh-60": "60vh",
                "vh-65": "65vh",
                "vh-70": "70vh",
                "vh-80": "80vh",
                "vh-90": "90vh",
                "1/10": "10%",
                "2/10": "20%",
                "3/10": "30%",
                "3.5/10": "35%",
                "4/10": "40%",
                "5/10": "50%",
                "6/10": "60%",
                "7/10": "70%",
                "8/10": "80%",
                "9/10": "90%",
                "2px": "2px",
            },
            inset: {
                "1/5": "20%",
                "2/5": "40%",
                "3/5": "60%",
                "4/5": "80%",
                "1/2": "50%",
                "1/10": "10%",
                "2/10": "20%",
                "3/10": "30%",
                "3.5/10": "35%",
                "4/10": "40%",
                "5/10": "50%",
                "6/10": "60%",
                "7/10": "70%",
                "8/10": "80%",
                "9/10": "90%",
            },
            zIndex: {
                "-10": "-10",
                "-20": "-20",
                "-30": "-30",
                "-40": "-40",
            },
            animation: {
                "spin-slow": "spin 5s linear infinite",
                "ping-slow": "ping 5s cubic-bezier(0, 0, 0.2, 1) infinite",
            },
        },
    },
    variants: {
        extend: {
            backgroundImage: ["hover"],
        },
    },
    plugins: [],
};
